development:
  adapter: postgresql
  encoding: unicode
  database: chess
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: chess_test
  pool: 5
  username: gschool
  password:
